### ISSUE TITLE
提个小问题

### ISSUE THREAD

**Issue by LiuSky** [meitu/MPITextKit#11]
YYText 的 Text Attriutes Demo当中，我长按一个标签或者link，并不会像MPITextKit 那样子，直接就触发点击事件，而是当点击才会真正触发，不知道 MPITextKit 能否修改下。

**Comment by LiuSky** [comment]
微博也是类似，我长按link的时候有个背景颜色，但是并不会马上触发事件。

**Comment by wanhmr** [comment]
@LiuSky 暂时没有计划支持，因为目前的行为是更加与 UITextView 保持一致，这算是 feature 而不是 bug。

**Comment by LiuSky** [comment]
@wanhmr  嗯是的
