### ISSUE TITLE
UITableViewAutomaticDimension使用Masonry布局闪动

### ISSUE THREAD

**Issue by 2410495654** [meitu/MPITextKit#12]
[self.nameMPILabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(contentView).offset(12);
        make.left.equalTo(contentView);
        make.right.equalTo(contentView).offset(-12);
    }];

{
NSMutableAttributedString *text = [NSMutableAttributedString new];
            UIFont *font = [UIFont systemFontOfSize:14];
            
            image = [UIImage imageWithCGImage:image.CGImage scale:2 orientation:UIImageOrientationUp];
            MPITextAttachment *attach = [MPITextAttachment new];
            attach.content = image;
            NSMutableAttributedString *attachText = [[NSAttributedString attributedStringWithAttachment:attach] mutableCopy];
            [text appendAttributedString:attachText];
            
            [text appendAttributedString:[[NSAttributedString alloc] initWithString:@" " attributes:nil]];
            
            NSString *title = @"fffffffffffffffffff";
            [text appendAttributedString:[[NSAttributedString alloc] initWithString:title attributes:nil]];
            
            [text addAttribute:NSFontAttributeName value:font range:text.mpi_rangeOfAll];
            self.nameMPILabel.attributedText = text;
}

**Comment by wanhmr** [comment]
@2410495654 有具体 demo 吗？
