### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by lujun5678275** [meitu/MPITextKit#14]
UIScrollView里面添加MPILabel ，MPILabel编辑状态，长按选择后拖动选择框，有没有回调，让外层的UIScrollView也跟着滚动?

**Comment by wanhmr** [comment]
@lujun5678275 目前没有回调，但是 selectedRange 属性是跟随选中实时变更的。你或许可以添加一个 pan 手势去追踪改变。文本选择的 pan 手势是 MPITextInteractionManager 的 grabberPanGestureRecognizer。
