### ISSUE TITLE
replaceCharacters with MPITextAttachment got one strange error

### ISSUE THREAD

**Issue by ChaosTong** [meitu/MPITextKit#2]
e.g. attributedString like "aaa [fun][fun][fun] aaaaa"
i will replace [fun] to a image, with MPITextAttachment, using replaceCharacters function.
when the string like this "[a][b]" replace fine, but the string like "[a][a]" i won't get two image, i just a one twice width's image
but i change the MPITextAttachment to NSTextAttachment, just work fine.

**Comment by wanhmr** [comment]
see the commit: https://github.com/meitu/MPITextKit/pull/1/commits/b8a07414e44b845dd374ac5df7f213c91c07ff6b

**Comment by ChaosTong** [comment]
i upadted to 0.1.2 and on simulator iOS 13.0 it's work fine, but on my real device XR with iOS 13.4 still not work.

**Comment by wanhmr** [comment]
@ChaosTong Please try version 0.1.3 and see details in [MPITextAttributesSeparationViewController.m](https://github.com/meitu/MPITextKit/blob/master/Example/MPITextKit/ViewController/MPITextAttributesSeparationViewController.m)

**Comment by ChaosTong** [comment]
> @ChaosTong Please try version 0.1.3 and see details in [MPITextAttributesSeparationViewController.m](https://github.com/meitu/MPITextKit/blob/master/Example/MPITextKit/ViewController/MPITextAttributesSeparationViewController.m)

got it, add a entity it won't be merged
