### ISSUE TITLE
selectable = true时，在文本「MPITextLinkAttributeName」的范围外，文本内点击，则不会有任何响应，导致无法触发其他点击事件

### ISSUE THREAD

**Issue by jiasongs** [meitu/MPITextKit#21]
1、问题：selectable = true时，在文本「MPITextLinkAttributeName」的范围外，文本内点击，则不会有任何响应，导致无法触发其他点击事件。另外，点击除MPILabel外的地方，selectable的选中范围也不会消失。
2、场景：例如，我在UICollectionViewCell上加了MPILabel，给文本中的一小段文字加了「MPITextLinkAttributeName」实现富文本点击效果，如果我点击文本的其他区域就无法触发UICollectionView的`didSelectItemAtIndexPath`代理。
3、期望：开启selectable的情况下，但是未出现选择区域时，点击时MPILabel需要响应其他的点击事件。另外，点击除MPILabel外的地方也应该让选择区域消失
4、可复现的Demo:
「MPITextTruncatingViewController」里有注释的代码可以测试
<img width="804" alt="图片" src="https://user-images.githubusercontent.com/22904757/119215026-a1dc6580-bafd-11eb-8318-944a9dca94d3.png">
[MPITextKit-master.zip](https://github.com/meitu/MPITextKit/files/6525813/MPITextKit-master.zip)

**Comment by jiasongs** [comment]
用以下方法暂时解决了下
<img width="933" alt="图片" src="https://user-images.githubusercontent.com/22904757/119214476-c1718f00-baf9-11eb-9ebf-848046ead50c.png">
但是有可能会触发，不知道怎么解决
<img width="1093" alt="图片" src="https://user-images.githubusercontent.com/22904757/119214490-e0702100-baf9-11eb-9a5a-3e92a3d167db.png">

**Comment by wanhmr** [comment]
这里的难点在于，当 MPILabel 开启了 selectable 并且触摸 MPILabel 的时候，手势识别器不确定你是要 tap 还是 long press，所以 interactiveGestureRecognizer 响应了手势，而导致传递给 view 的 touches 被 cancel 掉了，也就导致 table view 的 didSelecteRow 没有被处罚。

如果要解决这个问题，需要改写目前的手势处理，但成本比较高，因此暂时不进行处理。

**Comment by jiasongs** [comment]
> 这里的难点在于，当 MPILabel 开启了 selectable 并且触摸 MPILabel 的时候，手势识别器不确定你是要 tap 还是 long press，所以 interactiveGestureRecognizer 响应了手势，而导致传递给 table view 的 touches 被 cancel 掉了，也就导致 table view 的 didSelecteRow 没有被响应。
> 
> 如果要解决这个问题，需要改写目前的手势处理，但成本比较高，因此暂时不进行处理。

OK

**Comment by wanhmr** [comment]
那我关掉啦。
