### ISSUE TITLE
使用中使用了selectable一些问题

### ISSUE THREAD

**Issue by huainanzi** [meitu/MPITextKit#22]
1.长按滑动选择过程中，触控不灵敏，触控过小。如何可以扩大范围。
2.选择滑动过程中。没有选择范围变化的监听回调。是否考虑加上。
还望大佬给予指点

**Comment by wanhmr** [comment]
@huainanzi 

> 1.长按滑动选择过程中，触控不灵敏，触控过小。如何可以扩大范围。

目前不支持自定义触碰范围，但是具体逻辑你可以查看 MPITextSelectionView.m 中的实现，通过更改宏定义 kGrabberTouchHitTestExtend、kKnobTouchHitTestExtend 更改触碰范围。

> 2.选择滑动过程中。没有选择范围变化的监听回调。是否考虑加上。

你可以使用 KVO 监听 selectedRange 的更改。

**Comment by huainanzi** [comment]
> @huainanzi
> 
> > 1.长按滑动选择过程中，触控不灵敏，触控过小。如何可以扩大范围。
> 
> 目前不支持自定义触碰范围，但是具体逻辑你可以查看 MPITextSelectionView.m 中的实现，通过更改宏定义 kGrabberTouchHitTestExtend、kKnobTouchHitTestExtend 更改触碰范围。
> 
> > 2.选择滑动过程中。没有选择范围变化的监听回调。是否考虑加上。
> 
> 你可以使用 KVO 监听 selectedRange 的更改。
好的，谢谢
