### ISSUE TITLE
MPITextEffectWindow的写法会导致横竖屏切换异常

### ISSUE THREAD

**Issue by jiasongs** [meitu/MPITextKit#24]
**录屏**
https://user-images.githubusercontent.com/22904757/123887703-9003a300-d984-11eb-9945-923f01e04dd3.mp4

**如何重现**
1、info.plist只勾选Portrait
<img width="264" alt="图片" src="https://user-images.githubusercontent.com/22904757/123779830-28f2d980-d905-11eb-94bf-9de1bcc7e67b.png">
2、AppDeleagte里实现
<img width="1215" alt="图片" src="https://user-images.githubusercontent.com/22904757/123779966-47f16b80-d905-11eb-879f-5f5af42720be.png">
3、MPITextSelectionViewController实现
<img width="567" alt="图片" src="https://user-images.githubusercontent.com/22904757/123887778-aa3d8100-d984-11eb-85f1-538173654e0f.png">
4、进入MPITextSelectionViewController后长按文字出现『菜单』然后选择区域，主要是「保证MPITextEffectWindow单例被创建」
5、横竖屏切换即可复现

可复现的Demo，全局搜索语句"MPITextKit/issues" 查看改动的地方
[MPITextKit_issue.zip](https://github.com/meitu/MPITextKit/files/6737394/MPITextKit_issue.zip)

**解决方案**
在Demo中，「MPITextEffectWindow.m的37行」，使用MPITextEffectWindowViewController代替UIViewController

**Comment by MainByElse** [comment]
same issue

**Comment by wanhmr** [comment]
@jiasongs 周末看一下，感谢反馈。
