### ISSUE TITLE
表情Unicode选择范围导致无法复制

### ISSUE THREAD

**Issue by huainanzi** [meitu/MPITextKit#27]
当文本是纯表情Unicode或者含有表情Unicode，进行选择复制，会导致复制失败，应该是选择的范围不正确。
MPITextKit_Example[1129:283853] Could not save pasteboard named com.apple.UIKit.pboard.general. Error: Error Domain=PBErrorDomain Code=2 "Cannot represent object of class __NSCFString as representation of type public.utf8-plain-text" UserInfo={NSLocalizedDescription=Cannot represent object of class __NSCFString as representation of type public.utf8-plain-text}
测试文本：😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸😸
还请作者能修复下

**Comment by huainanzi** [comment]
> @huainanzi 明天看一下。
大佬，这个问题有看吗

**Comment by wanhmr** [comment]
不好意思，我等会到家看一下……

**Comment by huainanzi** [comment]
> 不好意思，我等会到家看一下……

好的，麻烦了

**Comment by wanhmr** [comment]
@huainanzi 已修复。
