### ISSUE TITLE
文本中包含多个emoji表情显示会被拉伸

### ISSUE THREAD

**Issue by maxiaofei123** [meitu/MPITextKit#29]
![20221227172524](https://user-images.githubusercontent.com/6235049/147457165-1985a7a4-c7cf-4c89-802d-2f737662b251.jpg)
您好，这个库的可以任意选择文字功能太棒了，解决了我一直困扰的问题。超链接自定义效果使用起来也是很简洁方便。我现在遇到一个问题，我的文本字段图文混排的时候表情显示不太正常，会被拉伸。我用了两种写法，一种是找到表情位置进行替换。一种是直接appendAttributedString 都会出现拉伸问题

**Comment by maxiaofei123** [comment]
我再次尝试修改成如下方式

                MPITextAttachment *attachment = [MPITextAttachment new];
                attachment.content = image;
                attachment.contentMode = UIViewContentModeScaleAspectFit;
                attachment.verticalAligment =  MPITextVerticalAlignmentCenter;
                attachment.contentSize = CGSizeMake(20,20);
会出现间距问题
![20221228104832](https://user-images.githubusercontent.com/6235049/147522554-9eef103d-4640-4a2b-b59d-8f130101dd7a.jpg)

**Comment by wanhmr** [comment]
@maxiaofei123 如果可以的话，你提供一个 DEMO 我可能更容易提供解决方案。

**Comment by maxiaofei123** [comment]
您好 我在demo中做的修改，用模拟器12pro 测试出来会有多的间距问题。这个问题比较难复现在这里，我想应该跟我计算的size 大小有关系
![20221228124741](https://user-images.githubusercontent.com/6235049/147529337-9c4dd3a6-95b5-4dea-bb13-0ea6abe8b22a.jpg)
![20221228124830](https://user-images.githubusercontent.com/6235049/147529357-7c467cd8-68f4-49bb-a3b9-ba56bfa150b7.jpg)
[MPITextKit-master.zip](https://github.com/meitu/MPITextKit/files/7782880/MPITextKit-master.zip)

**Comment by wanhmr** [comment]
<img width="1314" alt="截屏2021-12-28 下午4 10 44" src="https://user-images.githubusercontent.com/14258488/147544101-3919c315-a10f-4477-8bf1-1b00ab509a6c.png">
@maxiaofei123 你改成这样看一下，这个问题其实在 DEMO 中有解决。

也可以参考这里：https://github.com/meitu/MPITextKit/issues/2

**Comment by maxiaofei123** [comment]
按照您说的这种方式修改，emoji 可以正常显示了。非常感谢您的帮助。
