### ISSUE TITLE
多个文本框同时选择文本，选择区域拖动多次后 ，无法再修改文本选择区域了。

### ISSUE THREAD

**Issue by maxiaofei123** [meitu/MPITextKit#32]
您好，请教一下，如果一个页面有多个文本框，那怎么可以做到文本选择只能对一个文本框进行操作。目前来看选中是多个文本可以共存，会导致选中的移动手势响应有问题。然后我可以把手势的响应范围增加么。

像图片中随意选择后，现在已经无法进行区域选择了
![20220118174917](https://user-images.githubusercontent.com/6235049/149913345-d26d66ed-96e3-4791-a8a6-2cd4dab44f5f.jpg)
。

**Comment by wanhmr** [comment]
@maxiaofei123 建议自己保存当前正在进行选择的 Label，选择下一个 Label 的时候，将上一个 Label 取消选中。
