### ISSUE TITLE
业务设置MPILabel的accessibilityLabel、accessibilityAttributedLabel不生效

### ISSUE THREAD

**Issue by jiasongs** [meitu/MPITextKit#33]
**问题：**
业务设置MPILabel的accessibilityLabel、accessibilityAttributedLabel不生效

**原因：**
MPILabel重写了「accessibilityLabel、accessibilityAttributedLabel」的getter方法，导致业务不管怎么设置都不会生效，苹果文档里这两个属性可以set。
<img width="506" alt="图片" src="https://user-images.githubusercontent.com/22904757/163754037-ef3ccc5f-afdc-4a89-9dc0-78e6c64619b6.png">

**建议：**
既满足外部可以设置accessibility，又不影响之前版本的适配
<img width="615" alt="图片" src="https://user-images.githubusercontent.com/22904757/163754630-0233d0ef-df14-469b-953c-456e1ff5052c.png">

**Comment by wanhmr** [comment]
Can you make a PR to fix this issue? thank you.

**Comment by jiasongs** [comment]
> Can you make a PR to fix this issue? thank you.

ok.
