### ISSUE TITLE
MPITextAttachment 内存泄露问题

### ISSUE THREAD

**Issue by xdh725** [meitu/MPITextKit#34]
在给出的Example MPITextKit Demo中测试点击Text Attachment，可以明显看到内存泄露导致的内存增长。

**Comment by xdh725** [comment]
问题找到了，是继承的NSTextAttachment自定义自身的循环引用问题，还在找问题的解决办法。

**Comment by xdh725** [comment]
MPITextAttachment里面实现了isEqual方法，当为true的时候，可以在下次进入时打破循环引用，但是实际环境重复进入某个视图，还是有大量的MPITextAttachment没有释放。

**Comment by jiasongs** [comment]
> MPITextAttachment里面实现了isEqual方法，当为true的时候，可以在下次进入时打破循环引用，但是实际环境重复进入某个视图，还是有大量的MPITextAttachment没有释放。

是缓存导致的延迟释放，MPITextCache缓存了MPITextRenderer，MPITextRenderer又持有了N个MPITextAttachment

**Comment by xdh725** [comment]
好的，有办法主动去清理缓存吗？
目前测试了极限情况，当内存达到峰值时，应该是触发了MemoryWarning，所以释放了一些缓存数据。
目前看来使用上应该不会有OOM的情况，但会占用大量内存资源，消耗用户的手机电量。

**Comment by jiasongs** [comment]
> 好的，有办法主动去清理缓存吗？ 目前测试了极限情况，当内存达到峰值时，应该是触发了MemoryWarning，所以释放了一些缓存数据。 目前看来使用上应该不会有OOM的情况，但会占用大量内存资源，消耗用户的手机电量。

目前MPILabel没提供相关的方法

**Comment by wanhmr** [comment]
@xdh725 建议你使用 MPILabel 的 textRenderer 属性，这样由你来管理缓存。

**Comment by xdh725** [comment]
好的，谢谢。
