### ISSUE TITLE
MPITextAttachment 内存泄漏

### ISSUE THREAD

**Issue by ishall1** [meitu/MPITextKit#37]
![image](https://user-images.githubusercontent.com/8748505/165019792-b16cc3f9-a943-4ee0-8541-e8420d78df7d.png)
![image](https://user-images.githubusercontent.com/8748505/165019765-73b5c4d3-9fb7-4a21-a2a4-aaefc2d05272.png)

在MPITextAttachment添加UIButton作为content，会导致内存泄漏，UIButton释放不掉

**Comment by wanhmr** [comment]
这是因为有内部缓存，可以看这里：https://github.com/meitu/MPITextKit/issues/34
