### ISSUE TITLE
选择文字时，触控拖拽范围无法增大

### ISSUE THREAD

**Issue by AnnaMa1992** [meitu/MPITextKit#38]
用demo 中MPITextSelectionViewController 修改成frame布局 ，选择文字时手势响应范围变小。基本都在绿色线条标记的地方才可以响应拖动。kGrabberTouchHitTestExtend  kKnobTouchHitTestExtend这两个值设置很大也没有用。请问怎么样才能增大触控拖动的响应范围，这样会使操作看起来更灵敏一点。

textView.backgroundColor = [UIColor lightGrayColor];
textView.textContainerInset = UIEdgeInsetsMake(30, 30, 30, 30);
 textView.frame = CGRectMake(30, 100, self.view.frame.size.width-60, 100)

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-26 at 11 13 27](https://user-images.githubusercontent.com/20902738/170424800-7d09bb18-f468-430a-ada8-c16a74758612.png)
;

**Comment by AnnaMa1992** [comment]
kGrabberTouchHitTestExtend 这个设置了但是没有效果，我们的产品应用可能文字就大多数只有一行到两行这样，我已经把frame 增加变局增大。但是好像没有起到什么效果。

**Comment by AnnaMa1992** [comment]
> @AnnaMa1992 建议你把视图的高度设置大一点，不要只有一行展示（例如 5 行）。如果你想灵敏度大一点，设置 kGrabberTouchHitTestExtend 大点就可以了。

kGrabberTouchHitTestExtend 这个设置了但是没有效果，我们的产品应用可能文字就大多数只有一行到两行这样，我已经把frame 增加变局增大。但是好像没有起到什么效果。

**Comment by AnnaMa1992** [comment]
> > @AnnaMa1992 建议你把视图的高度设置大一点，不要只有一行展示（例如 5 行）。如果你想灵敏度大一点，设置 kGrabberTouchHitTestExtend 大点就可以了。
> 
> kGrabberTouchHitTestExtend 这个设置了但是没有效果，我们的产品应用可能文字就大多数只有一行到两行这样，我已经把frame 增加变局增大。但是好像没有起到什么效果。

图片中整个灰色部分都是label 的frame

**Comment by wanhmr** [comment]
@AnnaMa1992 你可以用模拟器看一下（因为模拟器使用鼠标比手指更精确），我这边设置 kGrabberTouchHitTestExtend 大一点是生效的。

**Comment by wanhmr** [comment]
至于为什么说多行展示会好一点，因为可能手指移动的时候并没有平行移动，导致手指超出了文本的范围，这时候会影响文本的选择（这里可以优化体验，但是目前没时间）。

**Comment by AnnaMa1992** [comment]
> 至于为什么说多行展示会好一点，因为可能手指移动的时候并没有平行移动，导致手指超出了文本的范围，这时候会影响文本的选择（这里可以优化体验，但是目前没时间）。

好的，谢谢。
