### ISSUE TITLE
textAlignment &&  attributedText

### ISSUE THREAD

**Issue by ishall1** [meitu/MPITextKit#39]
发现给MPILabel设置textAlignment后，再给attributedText赋值，textAlignment是不会被用到，需要手动调一下
**- (void)mpi_setAlignment:(NSTextAlignment)alignment range:(NSRange)range;**
请问这里是基于什么考虑呢？

**Comment by wanhmr** [comment]
没什么考虑……就是单纯没做。因为一般都是用 attributedText。
