### ISSUE TITLE
文本选择的体验问题

### ISSUE THREAD

**Issue by huainanzi** [meitu/MPITextKit#40]
一般文本可以选择是长按文本触发的，现在遇到一个，假设第一次长按选择了全部的文本。然后触摸空白选择文本取消。这时候在文本上轻扫（比如：右下角往左上角扫动）就可以再触发选择而不是通过长按触发。麻烦作者看下

**Comment by LixinQian** [comment]
我也遇到这个问题了，有解决方案吗？
