### ISSUE TITLE
关于Swift项目使用Selection的问题

### ISSUE THREAD

**Issue by g-mars** [meitu/MPITextKit#43]
目前项目中使用Swift语言开发，在实现MPILabel 的协议方法- (void)labelWillBeginSelection:(MPILabel *)label selectedRange:(NSRangePointer)selectedRange ，不能设置selectedRange，在Swift中无法对方法中的参数进行修改，请求解决方案

**Comment by wanhmr** [comment]
@g-mars 
```swift
func labelWillBeginSelection(_ label: MPILabel, selectedRange: NSRangePointer) {
        selectedRange.pointee = NSMakeRange(1, 3)
}
```

**Comment by g-mars** [comment]
> @g-mars
> 
> ```swift
> func labelWillBeginSelection(_ label: MPILabel, selectedRange: NSRangePointer) {
>         selectedRange.pointee = NSMakeRange(1, 3)
> }
> ```

感谢回复，解决了问题
