### ISSUE TITLE
TextView的显示支持

### ISSUE THREAD

**Issue by Choice-Fei** [meitu/MPITextKit#50]
请问能否支持textview显示包含有MPITextAttachment的富文本？

**Comment by wanhmr** [comment]
@Choice-Fei 理论上是可以的，不过目前可能没有时间来支持。

**Comment by Choice-Fei** [comment]
> @Choice-Fei 理论上是可以的，不过目前可能没有时间来支持。

谢谢回答，不过这个需求应该是很实用的，大神后面如果有时间的话能否支持下。
