### ISSUE TITLE
iOS  17适配

### ISSUE THREAD

**Issue by Choice-Fei** [meitu/MPITextKit#51]
![image](https://github.com/meitu/MPITextKit/assets/13918369/38be7543-e4ba-43e8-8788-718b9f5f4228)

UIGraphicsBeginImageContextWithOptions，在iOS17上触发断言闪退，这个API17已经弃用，size的width和height有一个为0就会触发

**Comment by wanhmr** [comment]
Please try to version 0.2.1 and let me know if you have any questions.
