### ISSUE TITLE
关于添加Link偶现的Range越界问题

### ISSUE THREAD

**Issue by Choice-Fei** [meitu/MPITextKit#53]
![image](https://github.com/meitu/MPITextKit/assets/13918369/2bc4b531-460f-440c-95b7-418e3f686abb)
![image](https://github.com/meitu/MPITextKit/assets/13918369/81d82e9f-d93d-49b1-b489-81fe5d896e20)

这是我添加link的用法，是在tableViewCell里面使用的MPILabel。下图是友盟线上收集到Crash日志，目前暂时没找到复现场景，麻烦问下我的使用方法有问题么？如果没有，想问下大佬能否优化下这个越界的问题。

**Comment by wanhmr** [comment]
可以看下是否有在后台线程更新 attributedText 的操作

**Comment by Choice-Fei** [comment]
你好，你说的后台线程是指退到后台后还是指子线程？

**Comment by Choice-Fei** [comment]
> 可以看下是否有在后台线程更新 attributedText 的操作

您好，您说的后台线程是指App退到后台还是指的子线程?退到后台长链接未及时断掉的话可能会有，目前这个问题在上升趋势
![image](https://github.com/meitu/MPITextKit/assets/13918369/03ae8b10-b9e7-4b75-a413-2c8f62f80b02)

**Comment by Choice-Fei** [comment]
另外我发现还有一个问题，当我使用textRender属性后，如果两个富文本里MPITextAttachment的content是同一个UIImage，那么在渲染第二个富文本的时候第一个富文本对应的MPITextAttachment就会提前被销毁掉，也看了下之前的issue，是MPITextAttachment内部实现了isEqual方法造成的这个问题

**Comment by wanhmr** [comment]
@Choice-Fei 后台线程是指非主线程
attachment 中的

**Comment by Choice-Fei** [comment]
> @wanhmr 
> 2. 【那么在渲染第二个富文本的时候第一个富文本对应的MPITextAttachment就会提前被销毁掉，也看了下之前的issue，是MPITextAttachment内部实现了isEqual方法造成的这个问题】可以提供一下 DEMO 吗？提前销毁是什么意思呢。

![image](https://github.com/meitu/MPITextKit/assets/13918369/8a5fc8e9-e4dd-4bd1-98e0-a071152076a2)
这里控制台的<mpi_attachemnt_destory>是我在MPITextAttachment的dealloc方法里打印的
就是图中这种情况，这是一个tableView,一条消息对应一个Cell，每个cell生成对应的富文本，图中这两条消息是两个富文本，但内容是一样的，那个小喇叭就是我说的MPITextAttachment，下图是整个demo的实现代码
![image](https://github.com/meitu/MPITextKit/assets/13918369/9c1bbdd6-d9ae-465d-8601-0f41edf2ab95)

**Comment by Choice-Fei** [comment]
> @wanhmr
 > 2. 【那么在渲染第二个富文本的时候第一个富文本对应的MPITextAttachment就会提前被销毁掉，也看了下之前的issue，是MPITextAttachment内部实现了isEqual方法造成的这个问题】可以提供一下 DEMO 吗？提前销毁是什么意思呢。

提前销毁说的是指我reloadData之后，第二条的富文本渲染了后，第一个富文本的MPITextAttachment就走了dealloc方法，

**Comment by Choice-Fei** [comment]
> @wanhmr 
> 
> 3. MPITextKit 的设计上其实是倾向于不可变对象，只是当时没有完善好

请问一下，这里的意思是指MPITextKit不适合用于复用的场景么？（比如放在tableviewCell里使用）

**Comment by wanhmr** [comment]
@Choice-Fei 呃，当然可以用在 table view 的场景。
你试一下最新版本吧，看有没有解决 crash 问题。
