### ISSUE TITLE
autolayout布局换行问题

### ISSUE THREAD

**Issue by Choice-Fei** [meitu/MPITextKit#56]
![image](https://github.com/meitu/MPITextKit/assets/13918369/719d8823-f3a5-47e2-aa79-7069311276d9)

如图所示:两个都是MPILabel,想要换行必须设置preferredMaxLayoutWidth么？不设置的时候换行异常。

**Comment by wanhmr** [comment]
@Choice-Fei 建议设置 preferredMaxLayoutWidth，如果你有比较好的处理方式，欢迎提交 PR。
